// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: internal/proto/compliance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComplianceCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Results from diagnostic service
	ServiceName        string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IsEncrypted        bool   `protobuf:"varint,2,opt,name=is_encrypted,json=isEncrypted,proto3" json:"is_encrypted,omitempty"`
	EncryptionStandard string `protobuf:"bytes,3,opt,name=encryption_standard,json=encryptionStandard,proto3" json:"encryption_standard,omitempty"` // "TLS1.2", "TLS1.3", "SSL3", "none"
	FipsValidated      bool   `protobuf:"varint,4,opt,name=fips_validated,json=fipsValidated,proto3" json:"fips_validated,omitempty"`
	AnonymousAccess    bool   `protobuf:"varint,5,opt,name=anonymous_access,json=anonymousAccess,proto3" json:"anonymous_access,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ComplianceCheckRequest) Reset() {
	*x = ComplianceCheckRequest{}
	mi := &file_internal_proto_compliance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceCheckRequest) ProtoMessage() {}

func (x *ComplianceCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_compliance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceCheckRequest.ProtoReflect.Descriptor instead.
func (*ComplianceCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_compliance_proto_rawDescGZIP(), []int{0}
}

func (x *ComplianceCheckRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ComplianceCheckRequest) GetIsEncrypted() bool {
	if x != nil {
		return x.IsEncrypted
	}
	return false
}

func (x *ComplianceCheckRequest) GetEncryptionStandard() string {
	if x != nil {
		return x.EncryptionStandard
	}
	return ""
}

func (x *ComplianceCheckRequest) GetFipsValidated() bool {
	if x != nil {
		return x.FipsValidated
	}
	return false
}

func (x *ComplianceCheckRequest) GetAnonymousAccess() bool {
	if x != nil {
		return x.AnonymousAccess
	}
	return false
}

// NIST 800-171 control eval result
type NISTFinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ControlId     string                 `protobuf:"bytes,1,opt,name=control_id,json=controlId,proto3" json:"control_id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Compliant     bool                   `protobuf:"varint,3,opt,name=compliant,proto3" json:"compliant,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"` // "CRITICAL", "HIGH", "MEDIUM", "LOW"
	Remediation   string                 `protobuf:"bytes,5,opt,name=remediation,proto3" json:"remediation,omitempty"`
	Rationale     string                 `protobuf:"bytes,6,opt,name=rationale,proto3" json:"rationale,omitempty"` // Why this control matters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NISTFinding) Reset() {
	*x = NISTFinding{}
	mi := &file_internal_proto_compliance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NISTFinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NISTFinding) ProtoMessage() {}

func (x *NISTFinding) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_compliance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NISTFinding.ProtoReflect.Descriptor instead.
func (*NISTFinding) Descriptor() ([]byte, []int) {
	return file_internal_proto_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *NISTFinding) GetControlId() string {
	if x != nil {
		return x.ControlId
	}
	return ""
}

func (x *NISTFinding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NISTFinding) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

func (x *NISTFinding) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *NISTFinding) GetRemediation() string {
	if x != nil {
		return x.Remediation
	}
	return ""
}

func (x *NISTFinding) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type ComplianceCheckResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OverallCompliant bool                   `protobuf:"varint,1,opt,name=overall_compliant,json=overallCompliant,proto3" json:"overall_compliant,omitempty"`
	Findings         []*NISTFinding         `protobuf:"bytes,2,rep,name=findings,proto3" json:"findings,omitempty"`
	ComplianceScore  float32                `protobuf:"fixed32,3,opt,name=compliance_score,json=complianceScore,proto3" json:"compliance_score,omitempty"` // 20.0 to 30.0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ComplianceCheckResponse) Reset() {
	*x = ComplianceCheckResponse{}
	mi := &file_internal_proto_compliance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceCheckResponse) ProtoMessage() {}

func (x *ComplianceCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_compliance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceCheckResponse.ProtoReflect.Descriptor instead.
func (*ComplianceCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *ComplianceCheckResponse) GetOverallCompliant() bool {
	if x != nil {
		return x.OverallCompliant
	}
	return false
}

func (x *ComplianceCheckResponse) GetFindings() []*NISTFinding {
	if x != nil {
		return x.Findings
	}
	return nil
}

func (x *ComplianceCheckResponse) GetComplianceScore() float32 {
	if x != nil {
		return x.ComplianceScore
	}
	return 0
}

var File_internal_proto_compliance_proto protoreflect.FileDescriptor

const file_internal_proto_compliance_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/compliance.proto\x12\n" +
	"compliance\"\xe1\x01\n" +
	"\x16ComplianceCheckRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\fis_encrypted\x18\x02 \x01(\bR\visEncrypted\x12/\n" +
	"\x13encryption_standard\x18\x03 \x01(\tR\x12encryptionStandard\x12%\n" +
	"\x0efips_validated\x18\x04 \x01(\bR\rfipsValidated\x12)\n" +
	"\x10anonymous_access\x18\x05 \x01(\bR\x0fanonymousAccess\"\xc8\x01\n" +
	"\vNISTFinding\x12\x1d\n" +
	"\n" +
	"control_id\x18\x01 \x01(\tR\tcontrolId\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tcompliant\x18\x03 \x01(\bR\tcompliant\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12 \n" +
	"\vremediation\x18\x05 \x01(\tR\vremediation\x12\x1c\n" +
	"\trationale\x18\x06 \x01(\tR\trationale\"\xa6\x01\n" +
	"\x17ComplianceCheckResponse\x12+\n" +
	"\x11overall_compliant\x18\x01 \x01(\bR\x10overallCompliant\x123\n" +
	"\bfindings\x18\x02 \x03(\v2\x17.compliance.NISTFindingR\bfindings\x12)\n" +
	"\x10compliance_score\x18\x03 \x01(\x02R\x0fcomplianceScore2o\n" +
	"\x11ComplianceService\x12Z\n" +
	"\x0fCheckNIST800171\x12\".compliance.ComplianceCheckRequest\x1a#.compliance.ComplianceCheckResponseB9Z7github.com/UUCompSci/The-ANISTAS-Project/internal/protob\x06proto3"

var (
	file_internal_proto_compliance_proto_rawDescOnce sync.Once
	file_internal_proto_compliance_proto_rawDescData []byte
)

func file_internal_proto_compliance_proto_rawDescGZIP() []byte {
	file_internal_proto_compliance_proto_rawDescOnce.Do(func() {
		file_internal_proto_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_compliance_proto_rawDesc), len(file_internal_proto_compliance_proto_rawDesc)))
	})
	return file_internal_proto_compliance_proto_rawDescData
}

var file_internal_proto_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_compliance_proto_goTypes = []any{
	(*ComplianceCheckRequest)(nil),  // 0: compliance.ComplianceCheckRequest
	(*NISTFinding)(nil),             // 1: compliance.NISTFinding
	(*ComplianceCheckResponse)(nil), // 2: compliance.ComplianceCheckResponse
}
var file_internal_proto_compliance_proto_depIdxs = []int32{
	1, // 0: compliance.ComplianceCheckResponse.findings:type_name -> compliance.NISTFinding
	0, // 1: compliance.ComplianceService.CheckNIST800171:input_type -> compliance.ComplianceCheckRequest
	2, // 2: compliance.ComplianceService.CheckNIST800171:output_type -> compliance.ComplianceCheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_compliance_proto_init() }
func file_internal_proto_compliance_proto_init() {
	if File_internal_proto_compliance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_compliance_proto_rawDesc), len(file_internal_proto_compliance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_compliance_proto_goTypes,
		DependencyIndexes: file_internal_proto_compliance_proto_depIdxs,
		MessageInfos:      file_internal_proto_compliance_proto_msgTypes,
	}.Build()
	File_internal_proto_compliance_proto = out.File
	file_internal_proto_compliance_proto_goTypes = nil
	file_internal_proto_compliance_proto_depIdxs = nil
}
