// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: internal/proto/diagnostic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiagnosticsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetHost        string                 `protobuf:"bytes,1,opt,name=target_host,json=targetHost,proto3" json:"target_host,omitempty"`
	IncludePowershell bool                   `protobuf:"varint,2,opt,name=include_powershell,json=includePowershell,proto3" json:"include_powershell,omitempty"` // Use PowerShell for enhanced Windows info
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiagnosticsRequest) Reset() {
	*x = DiagnosticsRequest{}
	mi := &file_internal_proto_diagnostic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsRequest) ProtoMessage() {}

func (x *DiagnosticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_diagnostic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsRequest.ProtoReflect.Descriptor instead.
func (*DiagnosticsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_diagnostic_proto_rawDescGZIP(), []int{0}
}

func (x *DiagnosticsRequest) GetTargetHost() string {
	if x != nil {
		return x.TargetHost
	}
	return ""
}

func (x *DiagnosticsRequest) GetIncludePowershell() bool {
	if x != nil {
		return x.IncludePowershell
	}
	return false
}

type FTPConfig struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceName     string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	IsRunning       bool                   `protobuf:"varint,2,opt,name=is_running,json=isRunning,proto3" json:"is_running,omitempty"`
	IsFtps          bool                   `protobuf:"varint,3,opt,name=is_ftps,json=isFtps,proto3" json:"is_ftps,omitempty"`            // FTPS (FTP over TLS) vs plain FTP
	TlsVersion      string                 `protobuf:"bytes,4,opt,name=tls_version,json=tlsVersion,proto3" json:"tls_version,omitempty"` // TLS 1.2, 1.3, or empty if unencrypted
	Port            int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	AnonymousAccess bool                   `protobuf:"varint,6,opt,name=anonymous_access,json=anonymousAccess,proto3" json:"anonymous_access,omitempty"` // Dangerous for NIST compliance
	AllowedIps      []string               `protobuf:"bytes,7,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	FipsCompliant   string                 `protobuf:"bytes,8,opt,name=fips_compliant,json=fipsCompliant,proto3" json:"fips_compliant,omitempty"` // "true", "false", or "unknown"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FTPConfig) Reset() {
	*x = FTPConfig{}
	mi := &file_internal_proto_diagnostic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FTPConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FTPConfig) ProtoMessage() {}

func (x *FTPConfig) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_diagnostic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FTPConfig.ProtoReflect.Descriptor instead.
func (*FTPConfig) Descriptor() ([]byte, []int) {
	return file_internal_proto_diagnostic_proto_rawDescGZIP(), []int{1}
}

func (x *FTPConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FTPConfig) GetIsRunning() bool {
	if x != nil {
		return x.IsRunning
	}
	return false
}

func (x *FTPConfig) GetIsFtps() bool {
	if x != nil {
		return x.IsFtps
	}
	return false
}

func (x *FTPConfig) GetTlsVersion() string {
	if x != nil {
		return x.TlsVersion
	}
	return ""
}

func (x *FTPConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *FTPConfig) GetAnonymousAccess() bool {
	if x != nil {
		return x.AnonymousAccess
	}
	return false
}

func (x *FTPConfig) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *FTPConfig) GetFipsCompliant() string {
	if x != nil {
		return x.FipsCompliant
	}
	return ""
}

type DiagnosticsResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FtpConfig           *FTPConfig             `protobuf:"bytes,3,opt,name=ftp_config,json=ftpConfig,proto3" json:"ftp_config,omitempty"`
	RawPowershellOutput []string               `protobuf:"bytes,4,rep,name=raw_powershell_output,json=rawPowershellOutput,proto3" json:"raw_powershell_output,omitempty"` // For audit trail
	TimestampUnix       int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DiagnosticsResponse) Reset() {
	*x = DiagnosticsResponse{}
	mi := &file_internal_proto_diagnostic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiagnosticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosticsResponse) ProtoMessage() {}

func (x *DiagnosticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_diagnostic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosticsResponse.ProtoReflect.Descriptor instead.
func (*DiagnosticsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_diagnostic_proto_rawDescGZIP(), []int{2}
}

func (x *DiagnosticsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DiagnosticsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DiagnosticsResponse) GetFtpConfig() *FTPConfig {
	if x != nil {
		return x.FtpConfig
	}
	return nil
}

func (x *DiagnosticsResponse) GetRawPowershellOutput() []string {
	if x != nil {
		return x.RawPowershellOutput
	}
	return nil
}

func (x *DiagnosticsResponse) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

var File_internal_proto_diagnostic_proto protoreflect.FileDescriptor

const file_internal_proto_diagnostic_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/proto/diagnostic.proto\x12\n" +
	"diagnostic\"d\n" +
	"\x12DiagnosticsRequest\x12\x1f\n" +
	"\vtarget_host\x18\x01 \x01(\tR\n" +
	"targetHost\x12-\n" +
	"\x12include_powershell\x18\x02 \x01(\bR\x11includePowershell\"\x8e\x02\n" +
	"\tFTPConfig\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1d\n" +
	"\n" +
	"is_running\x18\x02 \x01(\bR\tisRunning\x12\x17\n" +
	"\ais_ftps\x18\x03 \x01(\bR\x06isFtps\x12\x1f\n" +
	"\vtls_version\x18\x04 \x01(\tR\n" +
	"tlsVersion\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12)\n" +
	"\x10anonymous_access\x18\x06 \x01(\bR\x0fanonymousAccess\x12\x1f\n" +
	"\vallowed_ips\x18\a \x03(\tR\n" +
	"allowedIps\x12%\n" +
	"\x0efips_compliant\x18\b \x01(\tR\rfipsCompliant\"\xe5\x01\n" +
	"\x13DiagnosticsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x124\n" +
	"\n" +
	"ftp_config\x18\x03 \x01(\v2\x15.diagnostic.FTPConfigR\tftpConfig\x122\n" +
	"\x15raw_powershell_output\x18\x04 \x03(\tR\x13rawPowershellOutput\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix2h\n" +
	"\x11DiagnosticService\x12S\n" +
	"\x10RunFTDiagnostics\x12\x1e.diagnostic.DiagnosticsRequest\x1a\x1f.diagnostic.DiagnosticsResponseB9Z7github.com/UUCompSci/The-ANISTAS-Project/internal/protob\x06proto3"

var (
	file_internal_proto_diagnostic_proto_rawDescOnce sync.Once
	file_internal_proto_diagnostic_proto_rawDescData []byte
)

func file_internal_proto_diagnostic_proto_rawDescGZIP() []byte {
	file_internal_proto_diagnostic_proto_rawDescOnce.Do(func() {
		file_internal_proto_diagnostic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_diagnostic_proto_rawDesc), len(file_internal_proto_diagnostic_proto_rawDesc)))
	})
	return file_internal_proto_diagnostic_proto_rawDescData
}

var file_internal_proto_diagnostic_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_diagnostic_proto_goTypes = []any{
	(*DiagnosticsRequest)(nil),  // 0: diagnostic.DiagnosticsRequest
	(*FTPConfig)(nil),           // 1: diagnostic.FTPConfig
	(*DiagnosticsResponse)(nil), // 2: diagnostic.DiagnosticsResponse
}
var file_internal_proto_diagnostic_proto_depIdxs = []int32{
	1, // 0: diagnostic.DiagnosticsResponse.ftp_config:type_name -> diagnostic.FTPConfig
	0, // 1: diagnostic.DiagnosticService.RunFTDiagnostics:input_type -> diagnostic.DiagnosticsRequest
	2, // 2: diagnostic.DiagnosticService.RunFTDiagnostics:output_type -> diagnostic.DiagnosticsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_diagnostic_proto_init() }
func file_internal_proto_diagnostic_proto_init() {
	if File_internal_proto_diagnostic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_diagnostic_proto_rawDesc), len(file_internal_proto_diagnostic_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_diagnostic_proto_goTypes,
		DependencyIndexes: file_internal_proto_diagnostic_proto_depIdxs,
		MessageInfos:      file_internal_proto_diagnostic_proto_msgTypes,
	}.Build()
	File_internal_proto_diagnostic_proto = out.File
	file_internal_proto_diagnostic_proto_goTypes = nil
	file_internal_proto_diagnostic_proto_depIdxs = nil
}
