// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: internal/proto/report.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePDFRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	DiagData      *DiagnosticsResponse     `protobuf:"bytes,1,opt,name=diag_data,json=diagData,proto3" json:"diag_data,omitempty"`
	NistData      *ComplianceCheckResponse `protobuf:"bytes,2,opt,name=nist_data,json=nistData,proto3" json:"nist_data,omitempty"`
	ReportTitle   string                   `protobuf:"bytes,3,opt,name=report_title,json=reportTitle,proto3" json:"report_title,omitempty"`
	Organization  string                   `protobuf:"bytes,4,opt,name=organization,proto3" json:"organization,omitempty"`
	PreparedBy    string                   `protobuf:"bytes,5,opt,name=prepared_by,json=preparedBy,proto3" json:"prepared_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePDFRequest) Reset() {
	*x = GeneratePDFRequest{}
	mi := &file_internal_proto_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePDFRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePDFRequest) ProtoMessage() {}

func (x *GeneratePDFRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePDFRequest.ProtoReflect.Descriptor instead.
func (*GeneratePDFRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_report_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePDFRequest) GetDiagData() *DiagnosticsResponse {
	if x != nil {
		return x.DiagData
	}
	return nil
}

func (x *GeneratePDFRequest) GetNistData() *ComplianceCheckResponse {
	if x != nil {
		return x.NistData
	}
	return nil
}

func (x *GeneratePDFRequest) GetReportTitle() string {
	if x != nil {
		return x.ReportTitle
	}
	return ""
}

func (x *GeneratePDFRequest) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *GeneratePDFRequest) GetPreparedBy() string {
	if x != nil {
		return x.PreparedBy
	}
	return ""
}

type GeneratePDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PdfBytes      []byte                 `protobuf:"bytes,2,opt,name=pdf_bytes,json=pdfBytes,proto3" json:"pdf_bytes,omitempty"` // Return PDF as bytes (or write to path)
	OutputPath    string                 `protobuf:"bytes,3,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePDFResponse) Reset() {
	*x = GeneratePDFResponse{}
	mi := &file_internal_proto_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePDFResponse) ProtoMessage() {}

func (x *GeneratePDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePDFResponse.ProtoReflect.Descriptor instead.
func (*GeneratePDFResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_report_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePDFResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GeneratePDFResponse) GetPdfBytes() []byte {
	if x != nil {
		return x.PdfBytes
	}
	return nil
}

func (x *GeneratePDFResponse) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

func (x *GeneratePDFResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_internal_proto_report_proto protoreflect.FileDescriptor

const file_internal_proto_report_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/report.proto\x12\x06report\x1a\x1finternal/proto/diagnostic.proto\x1a\x1finternal/proto/compliance.proto\"\xfc\x01\n" +
	"\x12GeneratePDFRequest\x12<\n" +
	"\tdiag_data\x18\x01 \x01(\v2\x1f.diagnostic.DiagnosticsResponseR\bdiagData\x12@\n" +
	"\tnist_data\x18\x02 \x01(\v2#.compliance.ComplianceCheckResponseR\bnistData\x12!\n" +
	"\freport_title\x18\x03 \x01(\tR\vreportTitle\x12\"\n" +
	"\forganization\x18\x04 \x01(\tR\forganization\x12\x1f\n" +
	"\vprepared_by\x18\x05 \x01(\tR\n" +
	"preparedBy\"\x92\x01\n" +
	"\x13GeneratePDFResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tpdf_bytes\x18\x02 \x01(\fR\bpdfBytes\x12\x1f\n" +
	"\voutput_path\x18\x03 \x01(\tR\n" +
	"outputPath\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2W\n" +
	"\rReportService\x12F\n" +
	"\vGeneratePDF\x12\x1a.report.GeneratePDFRequest\x1a\x1b.report.GeneratePDFResponseB9Z7github.com/UUCompSci/The-ANISTAS-Project/internal/protob\x06proto3"

var (
	file_internal_proto_report_proto_rawDescOnce sync.Once
	file_internal_proto_report_proto_rawDescData []byte
)

func file_internal_proto_report_proto_rawDescGZIP() []byte {
	file_internal_proto_report_proto_rawDescOnce.Do(func() {
		file_internal_proto_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_report_proto_rawDesc), len(file_internal_proto_report_proto_rawDesc)))
	})
	return file_internal_proto_report_proto_rawDescData
}

var file_internal_proto_report_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_report_proto_goTypes = []any{
	(*GeneratePDFRequest)(nil),      // 0: report.GeneratePDFRequest
	(*GeneratePDFResponse)(nil),     // 1: report.GeneratePDFResponse
	(*DiagnosticsResponse)(nil),     // 2: diagnostic.DiagnosticsResponse
	(*ComplianceCheckResponse)(nil), // 3: compliance.ComplianceCheckResponse
}
var file_internal_proto_report_proto_depIdxs = []int32{
	2, // 0: report.GeneratePDFRequest.diag_data:type_name -> diagnostic.DiagnosticsResponse
	3, // 1: report.GeneratePDFRequest.nist_data:type_name -> compliance.ComplianceCheckResponse
	0, // 2: report.ReportService.GeneratePDF:input_type -> report.GeneratePDFRequest
	1, // 3: report.ReportService.GeneratePDF:output_type -> report.GeneratePDFResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_report_proto_init() }
func file_internal_proto_report_proto_init() {
	if File_internal_proto_report_proto != nil {
		return
	}
	file_internal_proto_diagnostic_proto_init()
	file_internal_proto_compliance_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_report_proto_rawDesc), len(file_internal_proto_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_report_proto_goTypes,
		DependencyIndexes: file_internal_proto_report_proto_depIdxs,
		MessageInfos:      file_internal_proto_report_proto_msgTypes,
	}.Build()
	File_internal_proto_report_proto = out.File
	file_internal_proto_report_proto_goTypes = nil
	file_internal_proto_report_proto_depIdxs = nil
}
